global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using Shouldly;
global using System.Reflection;
global using ToolCart.Configuration;
global using ToolCart.ConsoleHelpers;
global using ToolCart.Foundation.Helpers;
global using ToolCart.Host;
global using ToolCart.Services;
global using Xunit;
global using static ToolCart.Tests.Collections;
