name: ToolCart Build

on:
  create:
    branches: 
      - release/**
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.CECCOMIL_NUGET }}
        nuget-version: '6.x'

    - name: Setup .NET8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/ToolCart/ToolCart.sln

    - name: Build
      run: dotnet build ./src/ToolCart/ToolCart.sln --no-restore --configuration $env:BUILD_CONFIG

    - name: Test
      run: dotnet test ./src/ToolCart/ToolCart.sln /p:Configuration=$env:BUILD_CONFIG --no-restore --verbosity normal

    - name: Publish (packages)
      if: startsWith(github.ref, 'refs/tags/v')
      run: nuget push **/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{ secrets.CECCOMIL_NUGET }} -SkipDuplicate